language: node_js
sudo: false
node_js:
  - "0.11"
  - "0.10"
before_script:
  - "npm install -g jshint"
after_script: 
  - "jshint ."
notifications:
  email:
    recipients:
      - david@mojang.com
      - amir@mojang.com
    on_success: change
    on_failure: always
