language: node_js
sudo: false
node_js:
  - "0.12"
  - "4.2.6"
  - "5.5"
before_script:
  - "npm install -g jshint"
after_script: 
  - "jshint ."
notifications:
  email:
    recipients:
      - david@mojang.com
    on_success: change
    on_failure: always
